# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'generator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerator.proto\x12\tgenerator\"<\n\rNumeroRequest\x12\r\n\x05num_a\x18\x01 \x01(\x05\x12\r\n\x05num_b\x18\x02 \x01(\x05\x12\r\n\x05num_c\x18\x03 \x01(\x05\"?\n\x11ResultadoResponse\x12\x12\n\nid_cliente\x18\x01 \x01(\x05\x12\x16\n\x0eresultado_suma\x18\x02 \x01(\x05\"?\n\x0c\x43onfirmacion\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tener\x18\x03 \x01(\x08\x32\\\n\x11GeneradorServicio\x12G\n\x0eProcesarNumero\x12\x1c.generator.ResultadoResponse\x1a\x17.generator.Confirmacionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMEROREQUEST']._serialized_start=30
  _globals['_NUMEROREQUEST']._serialized_end=90
  _globals['_RESULTADORESPONSE']._serialized_start=92
  _globals['_RESULTADORESPONSE']._serialized_end=155
  _globals['_CONFIRMACION']._serialized_start=157
  _globals['_CONFIRMACION']._serialized_end=220
  _globals['_GENERADORSERVICIO']._serialized_start=222
  _globals['_GENERADORSERVICIO']._serialized_end=314
# @@protoc_insertion_point(module_scope)
