version: "3.8"

services:
  java-consumer:
    build: .
    container_name: java-consumer
    restart: on-failure # Reinicia si RabbitMQ aún no está listo en la otra red
    networks:
      - rabbit_red

networks:
  rabbit_red:
    external: true
