# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: numeros.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'numeros.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnumeros.proto\x12\x07numeros\"\x19\n\x0b\x43lienteInfo\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\x06Vector\x12\x0f\n\x07numeros\x18\x01 \x03(\x05\"*\n\tResultado\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tresultado\x18\x02 \x01(\x05\">\n\x11RespuestaServidor\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x18\n\x10total_resultados\x18\x02 \x01(\x05\x32\x8a\x01\n\rNumeroService\x12\x36\n\rObtenerVector\x12\x14.numeros.ClienteInfo\x1a\x0f.numeros.Vector\x12\x41\n\x0f\x45nviarResultado\x12\x12.numeros.Resultado\x1a\x1a.numeros.RespuestaServidorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numeros_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTEINFO']._serialized_start=26
  _globals['_CLIENTEINFO']._serialized_end=51
  _globals['_VECTOR']._serialized_start=53
  _globals['_VECTOR']._serialized_end=78
  _globals['_RESULTADO']._serialized_start=80
  _globals['_RESULTADO']._serialized_end=122
  _globals['_RESPUESTASERVIDOR']._serialized_start=124
  _globals['_RESPUESTASERVIDOR']._serialized_end=186
  _globals['_NUMEROSERVICE']._serialized_start=189
  _globals['_NUMEROSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
