# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import numeros_pb2 as numeros__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in numeros_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NumeroServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerVector = channel.unary_unary(
                '/numeros.NumeroService/ObtenerVector',
                request_serializer=numeros__pb2.ClienteInfo.SerializeToString,
                response_deserializer=numeros__pb2.Vector.FromString,
                _registered_method=True)
        self.EnviarResultado = channel.unary_unary(
                '/numeros.NumeroService/EnviarResultado',
                request_serializer=numeros__pb2.Resultado.SerializeToString,
                response_deserializer=numeros__pb2.RespuestaServidor.FromString,
                _registered_method=True)


class NumeroServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerVector(self, request, context):
        """Cliente pide un vector (3 números)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarResultado(self, request, context):
        """Cliente envía el resultado de su cálculo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NumeroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerVector': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerVector,
                    request_deserializer=numeros__pb2.ClienteInfo.FromString,
                    response_serializer=numeros__pb2.Vector.SerializeToString,
            ),
            'EnviarResultado': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarResultado,
                    request_deserializer=numeros__pb2.Resultado.FromString,
                    response_serializer=numeros__pb2.RespuestaServidor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'numeros.NumeroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('numeros.NumeroService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NumeroService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/numeros.NumeroService/ObtenerVector',
            numeros__pb2.ClienteInfo.SerializeToString,
            numeros__pb2.Vector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarResultado(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/numeros.NumeroService/EnviarResultado',
            numeros__pb2.Resultado.SerializeToString,
            numeros__pb2.RespuestaServidor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
