version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit_red

  python-producer:
    build: .
    container_name: python-producer
    command: tail -f /dev/null # Mantiene el contenedor vivo para ejecutar comandos manuales
    depends_on:
      - rabbitmq
    networks:
      - rabbit_red

networks:
  rabbit_red:
    external: true
