# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"Q\n\x11\x45xpressionRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\x12\x18\n\x0b\x63lient_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_client_name\"v\n\x12\x45xpressionResponse\x12,\n\x07success\x18\x01 \x01(\x0b\x32\x19.calculator.SuccessResultH\x00\x12(\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x17.calculator.ErrorResultH\x00\x42\x08\n\x06result\"H\n\rSuccessResult\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x19\n\x11parsed_expression\x18\x02 \x01(\t\x12\r\n\x05steps\x18\x03 \x03(\t\",\n\x0b\x45rrorResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2^\n\x11\x43\x61lculatorService\x12I\n\x08\x45valuate\x12\x1d.calculator.ExpressionRequest\x1a\x1e.calculator.ExpressionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPRESSIONREQUEST']._serialized_start=32
  _globals['_EXPRESSIONREQUEST']._serialized_end=113
  _globals['_EXPRESSIONRESPONSE']._serialized_start=115
  _globals['_EXPRESSIONRESPONSE']._serialized_end=233
  _globals['_SUCCESSRESULT']._serialized_start=235
  _globals['_SUCCESSRESULT']._serialized_end=307
  _globals['_ERRORRESULT']._serialized_start=309
  _globals['_ERRORRESULT']._serialized_end=353
  _globals['_CALCULATORSERVICE']._serialized_start=355
  _globals['_CALCULATORSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
